

- name: ""
  connection: local
  hosts: localhost
  roles:
  - avinetworks.avisdk
  #- avinetworks.avimigrationtools
  vars_files:
  - answerfile.yaml

  tasks:
  - avi_vsvip:
      api_context: '{{api_context | default(omit)}}'
      api_version: 18.2.11
      cloud_ref: /api/cloud?name=Default-Cloud
      controller: '{{ controller }}'
      name: 192.168.130.200-vsvip
      password: '{{ password }}'
      state: '{{ state | default(omit)}}'
      tenant: admin
      tenant_ref: /api/tenant/?name=admin
      username: '{{ username }}'
      vip:
      - ip_address:
          addr: 192.168.130.200
          type: V4
        vip_id: '0'
      vrf_context_ref: /api/vrfcontext/?name=global
    name: 'Create or Update VsVip: 192.168.130.200-vsvip'
    tags:
      - ansible_vs
  - avi_virtualservice:
      api_context: '{{api_context | default(omit)}}'
      api_version: 18.2.11
      application_profile_ref: /api/applicationprofile/?name=System-HTTP
      cloud_ref: /api/cloud?name=Default-Cloud
      controller: '{{ controller }}'
      description: null
      enabled: false
      name: ansible_vs
      network_profile_ref: /api/networkprofile/?name=System-TCP-Proxy
      pool_ref: /api/pool/?name=ansible_vs_pool
      error_page_profile_ref: /api/errorpageprofile?name=error-page
      password: '{{ password }}'
      services:
      - enable_ssl: true
        port: '443'
      ssl_key_and_certificate_refs:
      - /api/sslkeyandcertificate/?name=System-Default-Cert
      ssl_profile_ref: /api/sslprofile/?name=System-Standard
      state: '{{ state | default(omit)}}'
      tenant: admin
      tenant_ref: /api/tenant/?name=admin
      traffic_enabled: false
      type: VS_TYPE_NORMAL
      username: '{{ username }}'
      vrf_context_ref: /api/vrfcontext/?name=global
      #vs_datascripts: []
      vsvip_ref: /api/vsvip/?name=192.168.130.200-vsvip
    name: 'Create or Update VirtualService: ansible_vs'
    tags:
      - ansible_vs
